[package]
name = "luarust-cli"
description = "The luarust command."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "luarust"
path = "src/main.rs"

[dependencies]
luarust-check = { path = "../luarust-check" }
luarust-diag = { path = "../luarust-diag" }
luarust-interp = { path = "../luarust-interp" }
luarust-lex = { path = "../luarust-lex" }
luarust-parse = { path = "../luarust-parse" }
