[workspace]
resolver = "3"
members = [
    "crates/luarust-check",
    "crates/luarust-cli",
    "crates/luarust-conf",
    "crates/luarust-core",
    "crates/luarust-diag",
    "crates/luarust-gen",
    "crates/luarust-interp",
    "crates/luarust-jit",
    "crates/luarust-lex",
    "crates/luarust-num",
    "crates/luarust-parse",
    "crates/luarust-run",
    "crates/luarust-vm",
]

default-members = [
    "crates/luarust-check",
    "crates/luarust-cli",
    "crates/luarust-conf",
    "crates/luarust-core",
    "crates/luarust-diag",
    "crates/luarust-gen",
    "crates/luarust-interp",
    "crates/luarust-lex",
    "crates/luarust-num",
    "crates/luarust-parse",
    "crates/luarust-run",
    "crates/luarust-vm",
]

[workspace.package]
version = "0.0.0"
edition = "2024"
license = "MIT"
authors = ["Tankun Sriket"]
repository = "https://github.com/Artificial-IntelligenceAI/Luarust"

[profile.release]
opt-level = 3
debug = true
