[package]
name = "luarust-jit"
description = "Compiling Luarust to machine code with LLVM, in memory, and running it."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
inkwell = { version = "0.10.0", features = ["llvm21-1"] }
luarust-check = { path = "../luarust-check" }
luarust-diag = { path = "../luarust-diag" }
luarust-num = { path = "../luarust-num" }
luarust-parse = { path = "../luarust-parse" }

[dev-dependencies]
luarust-interp = { path = "../luarust-interp" }
luarust-lex = { path = "../luarust-lex" }
luarust-vm = { path = "../luarust-vm" }
luarust-gen = { path = "../luarust-gen" }
